version:  "3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=SU2orange!"
    ports:
      - "1433:1433"
    volumes:
      - "mssql-2017-data:/var/opt/mssql"
  webapp:    
    build: app/.
    environment:
#      - "CONNSTR=DRIVER={ODBC Driver 17 for SQL Server};SERVER=mssql,1433;DATABASE=master;UID=sa;PWD=SU2orange!"
      - "FLASK_APP=app.py"
      - "FLASK_ENV=development"
      - "SCHEMA_PATH=/app/schemas"
      - "SQL_CLIENT_HOST=mssql"
      - "SQL_CLIENT_PORT=1433"
      - "SQL_CLIENT_USER=sa"
      - "SQL_CLIENT_PASS=SU2orange!"
      - "SQL_CLIENT_CMD=/opt/mssql-tools/bin/sqlcmd"
      - "RANDOM_SEED=0"
    ports: 
      - "5000:5000"
    links:
      - mssql
    volumes:
      - "./app/:/app/" # for now
      - "./schemas:/app/schemas"
#  superset:
#    build: superset/.
#    links:
#      - mssql
#    ports:
#      - "5088:8088"
#  omnidb:
#    image: t4skforce/omnidb:latest
#    links:
#      - mssql
#    ports:
#      - "5080:8000"
#      - "25482:25482"
volumes:
    mssql-2017-data: